# Diagnostics action, blocking ros_control loop and generating a protocol
#goal
string serial_no
string assembly_of
bool execution_L
bool execution_R
bool communication
---
#result
int8 result
int8 channel
---
#feedback
SVHDiagnosticsFinger[] fingers
