name: Iron

on:
  push:
  pull_request:
  schedule:
    # Run every Friday at 6:30 am to detect breaking APIs
    - cron: '30 6 * * 5'


jobs:
  industrial_ci:
    env:
      BEFORE_BUILD_TARGET_WORKSPACE: '.github/script/install_mujoco.sh'
      UPSTREAM_WORKSPACE: 'github:SCHUNK-SE-Co-KG/schunk_svh_library#main'
      ROSDEP_SKIP_KEYS: 'schunk_svh_library'
    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: iron, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
