name: Humble

on:
  push:
  pull_request:
  schedule:
    # Run every Friday at 6:30 am to detect breaking APIs
    - cron: '30 6 * * 5'


jobs:
  industrial_ci:
    env:
      BEFORE_BUILD_TARGET_WORKSPACE: '.github/script/install_mujoco.sh'
      AFTER_RUN_TARGET_TEST: 'cd /root/target_ws && cat log/latest_test/schunk_svh_tests/streams.log'
    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
